In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
from sklearn import datasets
import numpy as np

Loading the Dataset

In [ ]:
iris = datasets.load_iris()
numpy_data = np.array(iris.data)
numpy_label = np.array(iris.target)
label_names = np.array(iris.target_names)

Find the Pearson Correlation coefficient

In [ ]:
cov_matrix = np.cov(numpy_data, rowvar = False)
std_devs = np.sqrt(np.diag(cov_matrix))
Q = np.abs(cov_matrix / np.outer(std_devs, std_devs))
print(Q)

[[1.         0.11756978 0.87175378 0.81794113]
 [0.11756978 1.         0.4284401  0.36612593]
 [0.87175378 0.4284401  1.         0.96286543]
 [0.81794113 0.36612593 0.96286543 1.        ]]


Find the Relevance matrix

In [ ]:
# This cell indivisually find Relevance matrix and Redundency matrix
# ,but this is not my code i go it from chatGPT
# dude we are not learning we should use numpy for implementation for everything i say.

import numpy as np
from sklearn.datasets import load_iris
from sklearn.feature_selection import mutual_info_classif
from sklearn.feature_selection import mutual_info_regression

# Load Iris dataset
data = load_iris()
X = data.data  # Features (continuous)
y = data.target  # Target (discrete)

# Calculate the mutual information between each feature and the target class (classification)
mi_classif = mutual_info_classif(X, y)

# Calculate the mutual information between pairs of features
n_features = X.shape[1]
mi_features = np.zeros((n_features, n_features))

# Mutual information between each pair of features
for i in range(n_features):
    for j in range(i, n_features):
        # Calculate mutual information between features i and j
        mi_value = mutual_info_regression(X[:, [i]], X[:, [j]])[0]
        mi_features[i, j] = mi_value
        mi_features[j, i] = mi_value  # Ensure the matrix is symmetric

# Display mutual information results
print("Relevance (mutual information) between each feature and target:")
for i, feature_name in enumerate(data.feature_names):
    print(f"{feature_name}: {mi_classif[i]}")

print("\nCorrelation Matrix (mutual information) between features:")
print(mi_features)

Relevance (mutual information) between each feature and target:
sepal length (cm): 0.4802179192585092
sepal width (cm): 0.30931402205031056
petal length (cm): 0.9991366868490796
petal width (cm): 0.9922809812952726

Correlation Matrix (mutual information) between features:
[[3.2198285  0.23232559 0.83616079 0.60974561]
 [0.23232559 2.66909086 0.32342053 0.42996714]
 [0.83616079 0.32342053 3.18001897 1.23153237]
 [0.60974561 0.42996714 1.23153237 2.69329115]]


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for exam